### ISSUE TITLE
formatE164 error

### ISSUE THREAD

**Issue by MeghaY** [albeebe/phoneformat.js#14]
Hey, I was implementing a test file for phone numbers using protractor in angularjs and came across this error which I thought I should point it out.. 
error message:
```
Expected '+1123456' not to be defined.
	Error: Expected '+1123456' not to be defined.
```
code line:
```
  expect(formatE164('US','123456')).not.toBeDefined();
```
And I think formatE164 should return 'undefined' in this case instead of putting +1 in front of invalid U.S number...

**Comment by tommytcchan** [comment]
yeah this is not correct:

formatE164("US", "+6043553085");
> "+6043553085"

**Comment by albeebe** [comment]
That's because by adding the plus it's already in e164 format.  Remove the
plus and it will do what I think  you we're expecting.

**Comment by tommytcchan** [comment]
gotcha :bow:
