### ISSUE TITLE
How can i connect with Jquery validation plugin

### ISSUE THREAD

**Issue by thangamliv** [albeebe/phoneformat.js#15]
Hai Al Cheetah - 

This is wonderful plugin, am not familiar in javascript, but i need to validate phonenumber based on country like google signup validator, how can i inculude this plugin in to my Jquery validation plugin. if you can please help me. Thank you.

**Comment by sturdynut** [comment]
This is a really old issue and I am closing because this isn't necessarily a bug in the code.
