### ISSUE TITLE
Error in australia number

### ISSUE THREAD

**Issue by madvik** [albeebe/phoneformat.js#22]
This number is false for your rules : +61473448744
Source : https://www.facebook.com/NerrigundahBlueberries/info?tab=page_info
Thanks

**Comment by D-Bullock** [comment]
Update the library from Google, doing so made that number work for me. [Instructions are here](https://github.com/albeebe/phoneformat.js#is-phoneformatjs-in-sync-with-the-latest-libphonenumber)

**Comment by madvik** [comment]
Thanks,

But I don't understand. The result is a google code like this:
```
var COMPILED = !0, goog = goog || {};
goog.global = this;
goog.isDef = function(a) {
  return void 0 !== a;
};
...
```
And my code is like this:
```
/*
Compiled Tuesday November 19, 2013 at 12:18pm America/New_York
Version: libphonenumber r622
...
*/
function countryForE164Number(phone) {
       ....
```

**Comment by D-Bullock** [comment]
That's fine. Replace your code with the google compiled code. The functions are all the same, it's just missing some comments.
