### ISSUE TITLE
bower install phoneformat.js#1.0.0 --save fails

### ISSUE THREAD

**Issue by andidev** [albeebe/phoneformat.js#25]
It is not possible to specify the version to install in the bower.json file since you have not created a git tag for the release version 1.0.0.

It is a part of the release process to create a tag in git with the release version name. See http://bower.io/docs/creating-packages/

Please create the git branch 1.0.0 with 
```
git br 1.0.0
```
and then push it to github with 
```
git push origin 1.0.0
```

to fix this issue

**Comment by sturdynut** [comment]
Will fix this asap as well, thank you @andidev!

**Comment by sturdynut** [comment]
Should be good to go.
