### ISSUE TITLE
Phoneformat api is duplicated in js files

### ISSUE THREAD

**Issue by andidev** [albeebe/phoneformat.js#26]
It looks like there is something wrong with the grunt build configuration since the API functions seems to be included more than once

e.g. the `formatInternational` method can be found on [line 978](https://github.com/albeebe/phoneformat.js/blob/master/dist/phone-format.js#L978) and [line 1968](https://github.com/albeebe/phoneformat.js/blob/master/dist/phone-format.js#L1968)
in `phone-format.js` file.
This problem occurs for all other files as well.

This is critical since the files size is quite large (865.901 kb unminimized). It looks like it is twice as large as the `google-libraries.js` file.

**Comment by andidev** [comment]
Looks like there is some serious build issues with buildscript

running grunt gives the following error:
```

Running "uglify:original" (uglify) task
>> Destination dist/phone-format.min.js not written because src files were empty.
>> No files created.

```

**Comment by sturdynut** [comment]
Thanks for bringing this up, I will look into it asap.  Thanks!

**Comment by andidev** [comment]
Thanks, seems to be some other problems. I'm working on a fix. Expect a PR soon.

**Comment by andidev** [comment]
So here it is. Fixed the major build issues. Needed to do a workaround in the Gruntfile. See comment in file on that.

**Comment by sturdynut** [comment]
LGTM!  Thank you @andidev.  :)
