### ISSUE TITLE
bower installs incorrect version of phoneformat

### ISSUE THREAD

**Issue by andidev** [albeebe/phoneformat.js#29]
It seems as you forgot to pull the changes before creating the 1.0.1 tag. So the tagged version in actually the same version as 1.0.0. This will cause bower to download the wrong version.

You need to remove the local and remote 1.0.1 tag, pull the latest changes t local local repo and then recreate and push the 1.0.1 tag again. Here's a cheatsheet

git tag -d 1.0.1
git push --delete origin 1.0.1
git pull
git tag 1.0.1
git push origin 1.0.1

**Comment by sturdynut** [comment]
**Doh!  Please try again.**
![DOH!](http://likesofme.files.wordpress.com/2013/11/homer-doh-tipping-app-review.gif)
