### ISSUE TITLE
Need to add to Bower.IO

### ISSUE THREAD

**Issue by robertbaker** [albeebe/phoneformat.js#32]
You actually need to add this to Bower.IO 

`bower register phoneformatjs https://github.com/albeebe/phoneformat.js`

https://github.com/elad/phoneformat/issues/4 is currently using phoneformat

**Comment by HadrienPierart** [comment]
Yes please register your library, especially as addind it through using the link of the github repo generates an error when using wiredep as the lib name contains a dot...
(This has also been bothering me with spin.js)

**Comment by alexkavon** [comment]
This is on bower.io under phoneformat.js I've included a pull request to include install instructions

**Comment by sturdynut** [comment]
Like @alexkavon said, it is listed under "phoneformat.js"

`bower install phoneformat.js` should do it.
