### ISSUE TITLE
Make package.json compatible with npm

### ISSUE THREAD

**Issue by vcarel** [albeebe/phoneformat.js#35]
I can't install phoneformat.js as a dependency in my npm's package.json, because the name field is missing.
Thanks !

**Comment by robertbaker** [comment]
+1 please register on NPM, takes only a few minutes to edit the json to add a main (point to the amd version) and register via npm register (i think that's the command)

**Comment by robertbaker** [comment]
see https://github.com/elad/phoneformat

**Comment by vcarel** [comment]
@robertbaker Thanks for the link... But does it mean that albeebe does not maintain anymore his repo ?

**Comment by robertbaker** [comment]
No. That fork is considered better because it can be updated with a script
instead of hand editing. Not sure why a PR wasn't done to push the changes
upstream.

**Comment by sturdynut** [comment]
Please try `npm install phoneformat.js` now. :)
