### ISSUE TITLE
False verification prefix

### ISSUE THREAD

**Issue by st4rg33k** [albeebe/phoneformat.js#44]
The function isValidNumber return true for CH country format but is false. 
Prefix for **switzerland is 0041** but with 0031(and other) return true.
console.log: **number** and **isValidNumber**
![console log](https://cloud.githubusercontent.com/assets/1897591/10285109/a64a53f0-6b87-11e5-9e4e-58be9e4fec0d.jpg)

**Comment by sturdynut** [comment]
This is appears to be a bug in Google's code.  They for whatever reason are returning "NL" as the region for 0031, even when you pass in "CH".  Not sure what to tell you. :/
